#-------------------------------
# Site Settings
title: Bitcoin UX Research
logo: '/images/logo.svg' # You can add own logo. For example '/images/logo.png'.
logo_dark: '/images/logo-dark.svg'
description: Website which will hold public data which will be avaliable to the ecosysystem of Bitcoin builders
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Toolkit'
      url: '/toolkit/'
    - title: 'Reports'
      url: '/reports/'
    - title: 'About'
      url: '/about/'

#-------------------------------
# Author Settings
author:
  author_name: James Brown
  author_avatar: '/images/01-1.jpg'


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_role: Understand ∙ Design ∙ Build
  hero_title: Understanding users drives Bitcoin adoption. Research-backed insights for better Bitcoin experiences.
  hero_button_text: Get Insights
  hero_button_link: "/reports/"


#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: Bitcoin UX Research Toolkit
  projects_description: Wondering how people use your product? What functionality they need? Or what they might be struggling with?


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: From My Blog
  blog_description: Dive into a world of creativity and inspiration through my blog. Here, I share insights into my artistic process, design trends, and the stories behind my latest projects.


#-------------------------------
# About Section Settings
about:
  enable: true
  about_image: '/images/01.jpg'
  about_title: Made by
  about_description: This has been created by the Bitcoin Design Community, an online community of bitcoin builders. It is our wish that the insights and tools you find here will empoer you as a builder to build with humans at the center of everything you do.

#-------------------------------
# Social Links
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
